name: Build APK with Buildozer

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential zip unzip openjdk-11-jdk python3-pip git ant \
          autoconf automake libtool libltdl-dev

        pip install --upgrade pip
        pip install Cython==0.29.33 virtualenv buildozer

    - name: Install Android SDK and Build-tools
      run: |
        mkdir -p ~/.buildozer/android/platform
        cd ~/.buildozer/android/platform

        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
        unzip -q cmdline-tools.zip -d temp-tools

        mkdir -p android-sdk/cmdline-tools/latest
        mv temp-tools/cmdline-tools/* android-sdk/cmdline-tools/latest/

        mkdir -p android-sdk/tools/bin
        ln -s $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager android-sdk/tools/bin/sdkmanager

        yes | android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=android-sdk \
          "platform-tools" \
          "platforms;android-31" \
          "build-tools;31.0.0" \
          "ndk;23.1.7779620"

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: kivy-apk
        path: bin/*.apk
